/**
 * Git Hooks CLI Command
 *
 * Manages git hook installation, uninstallation, and execution.
 */

import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";
import { GitHookRunner, GitHookName } from "../core/git-hook-runner.js";

interface GitHooksConfig {
  enabled: boolean;
  lifecycle?: {
    commitScoped?: string[];
    archive?: {
      enabled?: boolean;
      dir?: string;
    };
  };
  hooks?: Record<string, any>;
}

function loadMainConfig(targetDir: string): any {
  const configPath = path.join(targetDir, ".harness", "config.yaml");
  if (!fs.existsSync(configPath)) return null;
  const content = fs.readFileSync(configPath, "utf-8");
  return yaml.load(content) as any;
}

export async function runGitHooks(args: string[]): Promise<void> {
  const subcommand = args[0];
  const targetDir = process.cwd();
  const harnessDir = path.join(targetDir, ".harness");

  if (!fs.existsSync(harnessDir)) {
    console.error("❌ .harness directory not found. Run 'hannah init' first.");
    process.exit(1);
  }

  const mainConfig = loadMainConfig(targetDir);
  const gitHooksConfig: GitHooksConfig | undefined = mainConfig?.gitHooks;

  // Show help for help command or no subcommand
  if (
    !subcommand ||
    subcommand === "help" ||
    subcommand === "--help" ||
    subcommand === "-h"
  ) {
    showHelp();
    return;
  }

  // For install, allow even if not enabled yet
  if (!gitHooksConfig?.enabled && subcommand !== "install") {
    console.log("ℹ️  Git hooks are not enabled in .harness/config.yaml");
    console.log("   Set 'gitHooks.enabled: true' to enable.");
    return;
  }

  switch (subcommand) {
    case "install":
      await installGitHooks(targetDir, gitHooksConfig || { enabled: true });
      break;
    case "uninstall":
      await uninstallGitHooks(targetDir, gitHooksConfig || { enabled: true });
      break;
    case "status":
      await showGitHooksStatus(targetDir, gitHooksConfig || { enabled: true });
      break;
    case "run":
      await runGitHook(targetDir, gitHooksConfig || { enabled: true }, args[1]);
      break;
    case "list":
      await listGitHooks(gitHooksConfig || { enabled: true });
      break;
    default:
      showHelp();
  }
}

async function installGitHooks(targetDir: string, config: any): Promise<void> {
  const gitDir = path.join(targetDir, ".git");
  const hooksDir = path.join(gitDir, "hooks");

  if (!fs.existsSync(gitDir)) {
    console.error("❌ Not a git repository (.git directory not found)");
    process.exit(1);
  }

  if (!fs.existsSync(hooksDir)) {
    fs.mkdirSync(hooksDir, { recursive: true });
  }

  const hooksToInstall = Object.keys(config.hooks || {}).filter(
    (hook) => config.hooks[hook] !== false,
  );

  if (hooksToInstall.length === 0) {
    console.log("ℹ️  No hooks configured in gitHooks.hooks");
    return;
  }

  console.log("📦 Installing git hooks...\n");

  for (const hookName of hooksToInstall) {
    const hookPath = path.join(hooksDir, hookName);
    const backupPath = `${hookPath}.hannah-backup`;

    // Backup existing hook if present
    if (fs.existsSync(hookPath)) {
      const content = fs.readFileSync(hookPath, "utf-8");
      if (!content.includes("# Generated by hannah")) {
        fs.writeFileSync(backupPath, content, "utf-8");
        console.log(
          `  📋 Backed up existing ${hookName} → ${hookName}.hannah-backup`,
        );
      }
    }

    // Generate hook script
    const hookScript = generateHookScript(hookName);
    fs.writeFileSync(hookPath, hookScript, { mode: 0o755 });
    console.log(`  ✅ Installed ${hookName}`);
  }

  console.log(`\n✅ Git hooks installed: ${hooksToInstall.join(", ")}`);
}

async function uninstallGitHooks(
  targetDir: string,
  config: any,
): Promise<void> {
  const hooksDir = path.join(targetDir, ".git", "hooks");

  if (!fs.existsSync(hooksDir)) {
    console.log("ℹ️  No hooks directory found");
    return;
  }

  const hooksToUninstall = Object.keys(config.hooks || {});

  console.log("🗑️  Uninstalling git hooks...\n");

  for (const hookName of hooksToUninstall) {
    const hookPath = path.join(hooksDir, hookName);
    const backupPath = `${hookPath}.hannah-backup`;

    if (fs.existsSync(hookPath)) {
      const content = fs.readFileSync(hookPath, "utf-8");
      if (content.includes("# Generated by hannah")) {
        fs.unlinkSync(hookPath);
        console.log(`  ✅ Removed ${hookName}`);

        // Restore backup if exists
        if (fs.existsSync(backupPath)) {
          fs.copyFileSync(backupPath, hookPath);
          fs.unlinkSync(backupPath);
          console.log(`  📋 Restored backup → ${hookName}`);
        }
      } else {
        console.log(`  ⚠️  Skipped ${hookName} (not generated by hannah)`);
      }
    }
  }

  console.log("\n✅ Git hooks uninstalled");
}

async function showGitHooksStatus(
  targetDir: string,
  config: any,
): Promise<void> {
  const hooksDir = path.join(targetDir, ".git", "hooks");
  const configuredHooks = Object.keys(config.hooks || {});

  console.log("Git Hooks Status");
  console.log("═══════════════════════════════════════\n");

  for (const hookName of configuredHooks) {
    const hookPath = path.join(hooksDir, hookName);
    const hookConfig = config.hooks[hookName];

    let status = "❌ not installed";
    if (fs.existsSync(hookPath)) {
      const content = fs.readFileSync(hookPath, "utf-8");
      if (content.includes("# Generated by hannah")) {
        const callbackCount = hookConfig.callbacks?.length || 0;
        const builtinCount = hookConfig.builtin ? 1 : 0;
        status = `✅ installed (${builtinCount} builtin + ${callbackCount} callbacks)`;
      } else {
        status = "⚠️  installed (not by hannah)";
      }
    }

    console.log(`  ${hookName.padEnd(20)} ${status}`);
  }

  // Show lifecycle policy
  console.log("\nLifecycle Policy");
  console.log("═══════════════════════════════════════\n");

  const lifecycle = config.lifecycle || {};
  const commitScoped = lifecycle.commitScoped || [];
  const archiveEnabled = lifecycle.archive?.enabled || false;
  const archiveDir = lifecycle.archive?.dir || ".harness/archive";

  console.log(`  commit-scoped: ${commitScoped.join(", ") || "none"}`);
  console.log(
    `  archive:       ${archiveEnabled ? `enabled → ${archiveDir}` : "disabled"}`,
  );
}

async function runGitHook(
  targetDir: string,
  config: any,
  hookName: string,
): Promise<void> {
  if (!hookName) {
    console.error(
      "❌ Hook name required. Usage: hannah git-hooks run <hook-name>",
    );
    process.exit(1);
  }

  const hookConfig = config.hooks?.[hookName];
  if (!hookConfig) {
    console.error(`❌ Hook '${hookName}' not configured`);
    process.exit(1);
  }

  const runner = new GitHookRunner(targetDir);
  const result = await runner.runHook(hookName as GitHookName, hookConfig);

  if (!result.success) {
    console.error(`\n❌ Hook '${hookName}' failed`);
    process.exit(1);
  }

  console.log(`\n✅ Hook '${hookName}' completed successfully`);
}

async function listGitHooks(config: any): Promise<void> {
  const hooks = config.hooks || {};

  console.log("Configured Callbacks");
  console.log("═══════════════════════════════════════\n");

  for (const [hookName, hookConfig] of Object.entries(hooks)) {
    if (hookConfig === false) continue;

    console.log(`${hookName}:`);

    const cfg = hookConfig as any;

    // Show builtin callbacks
    if (cfg.builtin) {
      if (cfg.builtin.clearArtifacts) {
        const artifacts = config.lifecycle?.commitScoped || [];
        console.log(
          `  [builtin] clear-artifacts    → clears ${artifacts.join(", ")}`,
        );
      }
      if (cfg.builtin.archiveBeforeClear) {
        console.log(
          `  [builtin] archive-before     → archives to ${config.lifecycle?.archive?.dir || ".harness/archive"}`,
        );
      }
      if (cfg.builtin.resetDashboard) {
        console.log(`  [builtin] reset-dashboard    → resets dashboard state`);
      }
      if (cfg.builtin.logCommit) {
        console.log(`  [builtin] log-commit         → logs commit event`);
      }
    }

    // Show user callbacks
    if (cfg.callbacks) {
      for (const callback of cfg.callbacks) {
        const onFailure = callback.onFailure || "warn";
        console.log(
          `  [user]    ${callback.name.padEnd(18)} → ${callback.command} (on-failure: ${onFailure})`,
        );
      }
    }

    console.log();
  }
}

function generateHookScript(hookName: string): string {
  return `#!/usr/bin/env bash
# Generated by hannah git-hooks install
# Do not edit manually — changes will be overwritten

HANNAH_DIR="$(git rev-parse --show-toplevel)/.harness"

if [ -f "$HANNAH_DIR/config.yaml" ]; then
  npx hannah git-hooks run ${hookName} "$@"
  exit $?
fi

# If hannah is not configured, exit silently
exit 0
`;
}

function showHelp(): void {
  console.log(`
hannah git-hooks - Manage git hook interception

USAGE:
  hannah git-hooks <subcommand> [options]

SUBCOMMANDS:
  install              Install git hooks to .git/hooks/
  uninstall            Uninstall git hooks
  status               Show current git hooks status
  run <hook-name>      Manually trigger a hook's callback chain
  list                 List all configured callbacks

EXAMPLES:
  hannah git-hooks install
  hannah git-hooks status
  hannah git-hooks run pre-commit
  hannah git-hooks list

CONFIGURATION:
  Edit .harness/config.yaml to configure git hooks:

  gitHooks:
    enabled: true
    lifecycle:
      commitScoped: [traces, sessions, hook-logs]
      archive:
        enabled: true
        dir: .harness/archive
    hooks:
      pre-commit:
        builtin:
          clearArtifacts: true
          archiveBeforeClear: true
        callbacks:
          - name: "lint-check"
            command: "npm run lint"
            onFailure: abort
`);
}
