/**
 * File Scanner
 *
 * Scans file metadata to determine sensitivity, dependencies,
 * and modification risk.
 */

import * as fs from "node:fs";
import * as path from "node:path";

export interface FileMetadata {
  filePath: string;
  exists: boolean;
  size: number;
  extension: string;
  isGenerated: boolean;
  isSensitive: boolean;
  isConfig: boolean;
  isLockFile: boolean;
  isBinary: boolean;
  lineCount: number;
  lastModified: Date | null;
  dependencies: string[];
  riskLevel: "low" | "medium" | "high" | "critical";
}

export interface ScanResult {
  metadata: FileMetadata;
  warnings: string[];
  suggestions: string[];
}

const SENSITIVE_PATTERNS = [
  "**/.env",
  ".env",
  "**/.env.*",
  ".env.*",
  "**/*.env",
  "*.env",
  "**/*.pem",
  "*.pem",
  "**/*.key",
  "*.key",
  "**/*.cert",
  "*.cert",
  "**/*.p12",
  "*.p12",
  "**/secrets/**",
  "secrets/**",
  "**/credentials/**",
  "credentials/**",
  "**/.ssh/**",
  ".ssh/**",
  "**/id_rsa*",
  "id_rsa*",
  "**/.aws/credentials",
  ".aws/credentials",
];

const LOCK_FILE_PATTERNS = [
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
  "Gemfile.lock",
  "Cargo.lock",
  "poetry.lock",
  "composer.lock",
  "go.sum",
];

const GENERATED_INDICATORS = [
  "auto-generated",
  "autogenerated",
  "do not edit",
  "do not modify",
  "generated by",
  "code generated",
  "this file was generated",
];

const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg",
  ".pdf", ".zip", ".tar", ".gz", ".rar", ".7z",
  ".exe", ".dll", ".so", ".dylib", ".bin",
  ".woff", ".woff2", ".ttf", ".eot",
  ".mp3", ".mp4", ".avi", ".mov", ".wav",
  ".db", ".sqlite",
]);

const CONFIG_EXTENSIONS = new Set([
  ".yaml", ".yml", ".toml", ".ini", ".cfg", ".conf",
  ".json", ".xml", ".properties",
]);

const HIGH_RISK_EXTENSIONS = new Set([
  ".sql", ".migration",
]);

export function scanFile(filePath: string): FileMetadata {
  const normalized = filePath.replace(/\\/g, "/");
  const fileName = path.basename(normalized);
  const extension = path.extname(normalized).toLowerCase();
  const absolutePath = path.resolve(normalized);

  let exists = false;
  let size = 0;
  let lineCount = 0;
  let lastModified: Date | null = null;
  let isGenerated = false;
  const dependencies: string[] = [];

  try {
    if (fs.existsSync(absolutePath)) {
      exists = true;
      const stat = fs.statSync(absolutePath);
      size = stat.size;
      lastModified = stat.mtime;

      if (!BINARY_EXTENSIONS.has(extension) && size < 1_000_000) {
        try {
          const content = fs.readFileSync(absolutePath, "utf-8");
          lineCount = content.split("\n").length;

          const header = content.slice(0, 500).toLowerCase();
          isGenerated = GENERATED_INDICATORS.some((indicator) =>
            header.includes(indicator),
          );

          const importRegex = /(?:import|require|from)\s+['"]([^'"]+)['"]/g;
          let m;
          while ((m = importRegex.exec(content)) !== null) {
            dependencies.push(m[1]);
          }
        } catch {
          // Binary or unreadable file
        }
      }
    }
  } catch {
    // File not accessible
  }

  const isSensitive = isFileSensitive(normalized);
  const isLockFile = isFileLockFile(fileName);
  const isBinary = BINARY_EXTENSIONS.has(extension);
  const isConfig = CONFIG_EXTENSIONS.has(extension) || fileName.startsWith(".");
  const riskLevel = calculateRiskLevel(extension, isSensitive, isLockFile, isGenerated, isConfig);

  return {
    filePath: normalized,
    exists,
    size,
    extension,
    isGenerated,
    isSensitive,
    isConfig,
    isLockFile,
    isBinary,
    lineCount,
    lastModified,
    dependencies,
    riskLevel,
  };
}

function isFileSensitive(filePath: string): boolean {
  const normalized = filePath.toLowerCase();
  return SENSITIVE_PATTERNS.some((pattern) => {
    const regex = new RegExp(
      "^" +
      pattern
        .replace(/[.+^${}()|[\]\\]/g, "\\$&")
        .replace(/\*\*/g, ".*")
        .replace(/\*/g, "[^/]*") +
      "$",
    );
    return regex.test(normalized);
  });
}

function isFileLockFile(fileName: string): boolean {
  return LOCK_FILE_PATTERNS.includes(fileName);
}

function calculateRiskLevel(
  extension: string,
  isSensitive: boolean,
  isLockFile: boolean,
  isGenerated: boolean,
  isConfig: boolean,
): "low" | "medium" | "high" | "critical" {
  if (isSensitive) return "critical";
  if (isLockFile) return "high";
  if (isGenerated) return "high";
  if (HIGH_RISK_EXTENSIONS.has(extension)) return "high";
  if (isConfig) return "medium";
  return "low";
}

export function scanFileWithWarnings(filePath: string): ScanResult {
  const metadata = scanFile(filePath);
  const warnings: string[] = [];
  const suggestions: string[] = [];

  if (metadata.isSensitive) {
    warnings.push("File contains sensitive data (secrets, keys, credentials)");
    suggestions.push("Ask the human user to handle sensitive files");
    suggestions.push("Use environment variables instead of hardcoded secrets");
  }

  if (metadata.isLockFile) {
    warnings.push("File is a lock file managed by package manager");
    suggestions.push("Use the package manager (npm, pnpm, yarn) instead of editing directly");
  }

  if (metadata.isGenerated) {
    warnings.push("File appears to be auto-generated");
    suggestions.push("Modify the source/template instead of the generated file");
    suggestions.push("Run the code generator to update this file");
  }

  if (metadata.isBinary) {
    warnings.push("File is a binary format");
    suggestions.push("Use appropriate tools for binary file editing");
  }

  if (metadata.riskLevel === "critical") {
    warnings.push("CRITICAL: This file has the highest sensitivity level");
  }

  return { metadata, warnings, suggestions };
}
